### ISSUE TITLE
计算图像相似度问题

### ISSUE THREAD

**Issue by Biehebinghongcha** [ZhangFengze/QQLianLianKanCheat#2]
作者的这个代码写得太棒了，不过我有一点不太明白，为什么默认采用的是计算图像直方图的相似度，我试了之后效果挺差的。我改成计算三通道的平均phash后效果就挺好的了，基本不会判断出错。

**Comment by ZhangFengze** [comment]
你说得对，最近又捡回来试了试，高分辨率下效果很差

**Comment by ZhangFengze** [comment]
可以提个pr或者等我调一下

**Comment by ZhangFengze** [comment]
图像识别总是调不对，换成读内存了
